### ISSUE TITLE
when will you release the code

### ISSUE THREAD

**Issue by YanYan0716** [Meta-knowledge-Lab/DLB#1]
Hi~ I think this is a good work, thanks for your study, and when will you release the code,
with best wishes

**Comment by z383587717** [comment]
Hi~ I think this is a good work, thanks for your study, and when will you release the code,
with best wishes

**Comment by yiqings** [comment]
Hi @YanYan0716, we have already released the codes for CIFAR10/100 datasets.

**Comment by yiqings** [comment]
Hi @YanYan0716, as the codes are already established, we will close this issue.
