### ISSUE TITLE
LB loss 随着训练轮次增多，越来越大

### ISSUE THREAD

**Issue by ninisy** [Meta-knowledge-Lab/DLB#3]
起初lb loss大小约0.04左右
随着训练进行，增大到1左右。请问这是正常的吗？

**Comment by ZX-lang** [comment]
请问你是自己复现的代码吗

**Comment by yiqings** [comment]
Hi @ninisy. Apologies for the late reply. I am not very sure if we have communicated via email, because we have discuss this 'issue' with an NLPer on a very similar issue previously, where finally it is attributed to an implementation bug.

The email claims to encounter an unstable LB loss (i.e., either fluctuating or increasing) on the text classification task. The configurations: BERT as the backbone, alpha = 1, and temperature =3. However, eventually, the author identified an implementation bug (i.e., performing the LB loss on the wrong target). After she/he fixes the bug, LB loss keeps decreasing and approaches a performance improvement. 

If you still encounter this issue, please first check if the LB loss is performed on the correct target as in https://github.com/Meta-knowledge-Lab/DLB/blob/main/dlb.py.

**Comment by ZX-lang** [comment]
> Hi @ninisy. Apologies for the late reply. I am not very sure if we have communicated via email, because we have discuss this 'issue' with a NLPer on a very similar issue previous, where finally it is attributed to a implementation bug.
> 
> The email claim to encounter an unstable LB loss (i.e., either fluctuating or incleasing) on text classification task. The configurations: BERT as backbone, alpha = 1 and temperature =3. However, eventually the author identified an implementation bug (i.e., performing the LB loss on wrong target). After she/he fix the bug, LB loss keeps decreasing, and approaches an performance improvement.
> 
> If you still encounter this issue, please first check if the LB loss is performed on the correct target as in https://github.com/Meta-knowledge-Lab/DLB/blob/main/dlb.py.

你好请问一下图片输入到网路当中为啥 out = model.forward(imgs[:, 0, ...])采用这种形式，这样的不是只是输入图像的一个通道么

**Comment by yiqings** [comment]
> > Hi @ninisy. Apologies for the late reply. I am not very sure if we have communicated via email, because we have discuss this 'issue' with a NLPer on a very similar issue previous, where finally it is attributed to a implementation bug.
> > The email claim to encounter an unstable LB loss (i.e., either fluctuating or incleasing) on text classification task. The configurations: BERT as backbone, alpha = 1 and temperature =3. However, eventually the author identified an implementation bug (i.e., performing the LB loss on wrong target). After she/he fix the bug, LB loss keeps decreasing, and approaches an performance improvement.
> > If you still encounter this issue, please first check if the LB loss is performed on the correct target as in https://github.com/Meta-knowledge-Lab/DLB/blob/main/dlb.py.
> 
> 你好请问一下图片输入到网路当中为啥 out = model.forward(imgs[:, 0, ...])采用这种形式，这样的不是只是输入图像的一个通道么

Please refer to the dataloader in https://github.com/Meta-knowledge-Lab/DLB/blob/8949a4621072cbd9d0d9d78bf8d9fba0f1814ed0/my_dataloader.py#L224 where we process data into a `ndim=5` tensor `[B, num_augs, H, W, C]`

**Comment by ZX-lang** [comment]
> > > Hi @ninisy. Apologies for the late reply. I am not very sure if we have communicated via email, because we have discuss this 'issue' with a NLPer on a very similar issue previous, where finally it is attributed to a implementation bug.
> > > The email claim to encounter an unstable LB loss (i.e., either fluctuating or incleasing) on text classification task. The configurations: BERT as backbone, alpha = 1 and temperature =3. However, eventually the author identified an implementation bug (i.e., performing the LB loss on wrong target). After she/he fix the bug, LB loss keeps decreasing, and approaches an performance improvement.
> > > If you still encounter this issue, please first check if the LB loss is performed on the correct target as in https://github.com/Meta-knowledge-Lab/DLB/blob/main/dlb.py.
> > 
> > 
> > 你好请问一下图片输入到网路当中为啥 out = model.forward(imgs[:, 0, ...])采用这种形式，这样的不是只是输入图像的一个通道么
> 
> Please refer to the dataloader in
> 
> https://github.com/Meta-knowledge-Lab/DLB/blob/8949a4621072cbd9d0d9d78bf8d9fba0f1814ed0/my_dataloader.py#L224
> 
> where we process data into a `ndim=5` tensor `[B, num_augs, H, W, C]`

谢谢 我去看看
